author: eccentric_nz
description: 'Tracker for the Adventuring Time achievement. Players get the achievement after visiting these biomes at least once: Beach, Birch Forest, Birch Forest Hills, Cold Beach, Cold Taiga, Cold Taiga Hills, Deep Ocean, Desert, Desert Hills, Extreme Hills, Extreme Hills+, Forest, ForestHills, FrozenRiver, Ice Mountains, Ice Plains, Jungle, Jungle Edge, Jungle Hills, Mega Taiga, Mega Taiga Hills, Mesa, Mesa Plateau, Mesa Plateau F, Mushroom Island, MushroomIslandShore, Ocean, Plains, River, Roofed Forest, Savanna, Savanna Plateau, Stone Beach, Swampland, Taiga, and Taiga Hills'
main: me.eccentric_nz.adventuringtime.AdventuringTime
name: AdventuringTime
load: POSTWORLD
version: '1.0.1'
website: http://dev.bukkit.org/bukkit-plugins/adventuringtime
dev-url: http://dev.bukkit.org/bukkit-plugins/adventuringtime
url: http://dev.bukkit.org/bukkit-plugins/adventuringtime
permissions:
    adventuringtime.use:
        description: Allow a player to use the /at command.
        default: true
commands:
    adventuringtime:
        aliases: [atcheck,atchk,achk,biomecheck,biomechk,bchk]
        description: Show which biomes a player has visited, and those that are still undiscovered.
        usage: /<command> [v|u|g|t]
        permission: adventuringtime.use
        permission-message: You don't have the permission <permission> to use this command
